version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
    restart: always

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
    depends_on:
      - frontend
      - backend
    restart: always
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
      - ./uploads:/app/uploads
    environment:
      - PYTHONUNBUFFERED=1
      - YOUTUBE_API_KEY=${YOUTUBE_API_KEY}
      - REDIS_URL=redis://redis:6379/0
      - DATABASE_URL=postgresql://clipsummary:clipsummary@postgres:5432/clipsummary
      - SECRET_KEY=${SECRET_KEY:-mysecretkey}
      - JWT_SECRET=${JWT_SECRET:-jwtsecretkey}
      - JWT_ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      - MAX_UPLOAD_SIZE=10737418240
    env_file:
      - .env
    depends_on:
      - redis
      - postgres
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G

  redis:
    image: redis:alpine
    volumes:
      - redis-data:/data
    command: redis-server --maxmemory 1gb --maxmemory-policy allkeys-lru
    deploy:
      resources:
        limits:
          memory: 1.5G
        reservations:
          memory: 1G

  postgres:
    image: postgres:13
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=clipsummary
      - POSTGRES_USER=clipsummary
      - POSTGRES_DB=clipsummary
    ports:
      - "5432:5432"
    restart: always

volumes:
  redis-data:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/data/redis
      o: bind
  uploads:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/uploads
      o: bind
  postgres-data: