version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
    restart: always

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"  # Add HTTPS port
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./uploads:/var/www/uploads:ro  # Serve uploads as static files (read-only)
      - ./ssl:/etc/nginx/ssl:ro  # Mount SSL certificates
    depends_on:
      - frontend
      - backend
    restart: always

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
      - ./uploads:/app/uploads  # Bind mount for uploads (now used for temporary processing only)
      - ./models:/app/models  # Bind mount for models
    env_file:
      - .env
    depends_on:
      - redis
      - postgres
    restart: always
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu, compute, utility]

  redis:
    image: redis:alpine
    volumes:
      - redis-data:/data  # Named volume is fine for Redis
    env_file:
      - .env

  postgres:
    image: postgres:13
    volumes:
      - postgres-data:/var/lib/postgresql/data  # Named volume is fine for DB
    env_file:
      - .env
    ports:
      - "5432:5432"
    restart: always

volumes:
  redis-data:
  postgres-data: