version: '3.8'

services:
  frontend:
    image: clip-summary-frontend:latest
    volumes:
      - ./uploads:/app/public/uploads
    networks:
      - clipsummary-network

  nginx:
    image: nginx:alpine
    ports:
      - "3000:80"
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./frontend:/usr/share/nginx/html
    depends_on:
      - frontend
      - backend
    restart: always
    networks:
      - clipsummary-network

  backend:
    image: clip-summary-backend:latest
    volumes:
      - ./uploads:/app/uploads
    environment:
      - PYTHONUNBUFFERED=1
      - YOUTUBE_API_KEY=${YOUTUBE_API_KEY}
      - REDIS_URL=redis://redis:6379/0
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - clipsummary-network

  redis:
    image: redis:alpine
    restart: unless-stopped
    volumes:
      - redis-data:/data
    networks:
      - clipsummary-network

networks:
  clipsummary-network:
    driver: bridge

volumes:
  redis-data:
    driver: local