name: Simple Deploy

on:
  push:
    branches: [ dev, main, enhancement2 ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Connect to Tailscale
        uses: tailscale/github-action@v2
        with:
          authkey: ${{ secrets.TAILSCALE_KEY }}
      
      - name: Deploy to server
        run: |
          # Setup SSH
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          
          # SSH and deploy
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }} << 'EOF'
            cd ${{ secrets.DEPLOY_DIR }}
            git pull origin ${{ github.ref_name }}
            
            # Try docker compose (new format) first, then fall back to docker-compose
            if command -v docker &> /dev/null; then
              echo "Using docker compose (new format)"
              docker compose down || true
              docker compose up -d --build
            elif command -v docker-compose &> /dev/null; then
              echo "Using docker-compose (legacy format)"
              docker-compose down || true
              docker-compose up -d --build
            else
              echo "Neither docker compose nor docker-compose found!"
              echo "Available commands:"
              which docker || echo "docker not found"
              which docker-compose || echo "docker-compose not found"
              exit 1
            fi
          EOF