name: Build and Deploy

on:
  push:
    branches: [ dev, main, enhancement2 ]
  workflow_dispatch: # Allow manual triggering

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Install Tailscale
        uses: tailscale/github-action@v2
        with:
          authkey: ${{ secrets.TAILSCALE_KEY }}
      
      - name: SSH to server and deploy
        env:
          DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}  # This should be your server's Tailscale IP
          DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
          DEPLOY_SSH_KEY: ${{ secrets.DEPLOY_SSH_KEY }}
          DEPLOY_DIR: ${{ secrets.DEPLOY_DIR }}
        run: |
          # Setup SSH key
          mkdir -p ~/.ssh
          echo "$DEPLOY_SSH_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          
          # Add Tailscale IP to known hosts (bypass host key checking for Tailscale IPs)
          echo "Host 100.*" >> ~/.ssh/config
          echo "  StrictHostKeyChecking no" >> ~/.ssh/config
          echo "  UserKnownHostsFile /dev/null" >> ~/.ssh/config
          
          # Test connection first
          echo "Testing connection to $DEPLOY_HOST..."
          ssh -i ~/.ssh/id_rsa -o ConnectTimeout=10 $DEPLOY_USER@$DEPLOY_HOST "echo 'Connection successful'"
          
          # SSH to server and deploy via Tailscale
          ssh -i ~/.ssh/id_rsa $DEPLOY_USER@$DEPLOY_HOST << 'EOF'
            set -e
            
            # Navigate to deployment directory
            cd ${{ secrets.DEPLOY_DIR }}
            
            # Pull latest changes
            git fetch origin
            git checkout ${{ github.ref_name }}
            git pull origin ${{ github.ref_name }}
            
            # Stop existing containers
            docker-compose down || true
            
            # Build and deploy with docker-compose
            docker-compose build --no-cache
            docker-compose up -d
            
            # Wait for services to start
            echo "Waiting for services to start..."
            sleep 30
            
            # Check if services are running
            docker-compose ps
            
            # Show recent logs for debugging
            echo "=== Recent logs (last 30 lines) ==="
            docker-compose logs --tail=30
            
            echo "Deployment completed successfully!"
          EOF