name: Build and Deploy

on:
  push:
    branches: [ dev, main ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Install Tailscale
        uses: tailscale/github-action@v2
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci
      
      - name: SSH to server and deploy
        env:
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_USER: ${{ secrets.SSH_USER }}
        run: |
          # Setup SSH key
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H $SERVER_HOST >> ~/.ssh/known_hosts
          
          # SSH to server and deploy
          ssh -i ~/.ssh/id_rsa $SSH_USER@$SERVER_HOST << 'EOF'
            cd /path/to/clipSummary  # Update this path
            
            # Pull latest changes
            git pull origin ${{ github.ref_name }}
            
            # Build and deploy with docker-compose
            docker-compose down
            docker-compose build --no-cache
            docker-compose up -d
            
            # Optional: Clean up old images
            docker system prune -f
          EOF