name: Integration Tests

on:
  pull_request:
    branches: [ dev ]
    types: [ opened, synchronize, reopened ]
  push:
    branches: [ dev ]
  workflow_dispatch:

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    
    services:
      # Database service
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: clipsummary
          POSTGRES_PASSWORD: clipsummary
          POSTGRES_DB: clipsummary
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      
      # Cache service
      redis:
        image: redis:alpine
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for proper testing
      
      - name: Set up FFmpeg
        run: |
          sudo apt-get update && sudo apt-get install -y ffmpeg
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'
      
      - name: Install backend dependencies
        working-directory: ./backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-asyncio pytest-cov
      
      - name: Create test directories and prepare environment
        run: |
          mkdir -p backend/uploads
          mkdir -p backend/cache
          mkdir -p backend/.cache/huggingface
          touch backend/clipsummary.db  # Create empty database file
          
          # Create a small test video file
          ffmpeg -f lavfi -i color=c=blue:s=320x240:d=5 -c:v libx264 backend/tests/sample_video.mp4
      
      - name: Run integration tests with coverage
        working-directory: ./backend
        env:
          DATABASE_URL: postgresql://clipsummary:clipsummary@localhost:5432/clipsummary
          REDIS_URL: redis://localhost:6379/0
          SECRET_KEY: test_secret_key
          JWT_SECRET: test_jwt_secret
          JWT_ALGORITHM: HS256
          ACCESS_TOKEN_EXPIRE_MINUTES: 30
          MAX_UPLOAD_SIZE: 10737418240
          WHISPERX_DEVICE: cpu  # Use CPU for GitHub Actions
          TEST_MODE: true
        run: |
          pytest tests/integration/ -v --cov=. --cov-report=xml
      
      - name: Upload coverage report
        uses: codecov/codecov-action@v3
        with:
          file: ./backend/coverage.xml
          fail_ci_if_error: false
          flags: integration
      
      - name: Archive test results
        if: always()  # Run even if tests fail
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: |
            backend/tests/logs/
            backend/*.log
            backend/error.log