name: Integration Tests

on:
  pull_request:
    branches: [ dev ]
    types: [ opened, synchronize, reopened ]

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    needs: []  # Can run independently or add unit-tests as dependency
    
    services:
      redis:
        image: redis:alpine
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up FFmpeg
        run: |
          sudo apt-get update && sudo apt-get install -y ffmpeg
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'
      
      - name: Install Python dependencies
        working-directory: ./backend
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-asyncio pytest-mock
          pip install -r requirements.txt
      
      - name: Create test environment
        run: |
          mkdir -p backend/uploads backend/cache
          ffmpeg -f lavfi -i color=c=blue:s=320x240:d=5 -c:v libx264 backend/tests/sample_video.mp4
      
      - name: Run integration tests
        working-directory: ./backend
        env:
          DATABASE_URL: sqlite:///./test.db
          REDIS_URL: redis://localhost:6379/0
          SECRET_KEY: test_secret_key
          WHISPERX_DEVICE: cpu
          TEST_MODE: true
        run: |
          pytest tests/integration/ -v --tb=short